### ISSUE TITLE
Unauthorized use

### ISSUE THREAD

**Issue by captinc** [80036nd/RestoreM8-14-Code#1]
The following file/code in your repository is being used without authorization from me, the file/code's original creator. Additionally, no credit to me is given. Instead, you falsely claimed that you wrote this file/code yourself (see below code snippet). Please remove this file from your repository and remove all other references to my work from your work, which include other GitHub repositories and other projects. 

https://github.com/80036nd/RestoreM8-14-Code/blob/main/futurerestore_compile.sh

My original file states this: 
```
echo "This script was written by Capt Inc on January 4, 2021"
```
Your file states this: 
```
echo "This script was Written by 80036nd on Febuary 12, 2021"
```

For the record, the original file (written by me) can be found [here](https://captinc.me/tutorials/futurerestore_compile.sh).

**Comment by MatthewPierson** [comment]
@captinc [relevant commit](https://github.com/80036nd/RestoreM8-14-Code/commit/54208b9f90813d0eb9041364f571f518b4d40d77).

**Comment by 80036nd** [comment]
I am very sorry, I have now private the download of RestoreM8-14, In both README files I have now added futurerestore_compile.sh by Captinc. I also changed this. echo "This script was Written by Capt Inc on December 4, 2020, modified by 80036nd on February 12, 2021" I would hope you can forgive me and to have permission to youse your code in the app.

**Comment by captinc** [comment]
> I am very sorry, I have now private the download of RestoreM8-14, In both README files I have now added futurerestore_compile.sh by Captinc. I also changed this. echo "This script was Written by Capt Inc on December 4, 2020, modified by 80036nd on February 12, 2021" I would hope you can forgive me and to have permission to youse your code in the app.

I respectfully request that my work be entirely removed from your repository, as well as removed from your other projects.

**Comment by 80036nd** [comment]
I have removed your code out of this project, as this is the only project with your code.
